In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,37,7]], np.int64)

In [3]:
myarr[0,1]

6

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int64')

In [6]:
myarr[0,1] = 45

In [7]:
myarr

array([[ 3, 45, 37,  7]], dtype=int64)

**Array Creation: Conversion from other python structures**

In [8]:
listarray = np.array([[1,2,3], [5,8,5], [0,3,1]])

In [9]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [10]:
listarray.size

9

In [12]:
zeros = np.zeros((2,5))

In [13]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
rng = np.arange(15)

In [15]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
lspace = np.linspace(1,50,10)

In [19]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [20]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [21]:
ar = np.array(x)

In [22]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [23]:
ar.sum(axis=0)

array([12,  8,  9])

In [24]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [25]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [26]:
ar.flat

In [27]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [28]:
ar.ndim

2

In [29]:
ar.nbytes

36

In [30]:
one = np.array([1,3,4,634,2])

In [31]:
one.argmax()

3

In [32]:
one.argmin()

0

In [33]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [34]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [35]:
ar.argmin()

8

In [38]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [40]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [41]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [43]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [44]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [47]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [48]:
np.sum(ar)

29

In [50]:
ar.sum()

29

In [51]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [52]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [53]:
import sys

In [54]:
py_ar = [0,4,55,2]

In [55]:
np_ar = np.array(py_ar)

In [57]:
sys.getsizeof(1) * len(py_ar)

112

In [58]:
np_ar.itemsize * np_ar.size

16